### ISSUE TITLE
hypernat.sty找不到

### ISSUE THREAD

**Issue by ghost** [ZLCao/NJUBachelor#3]
我在windows平台下用miktex编译，报错找不到hypernat.sty文件，网上查到的结果是miktex 2.9版本不再支持hypernat.sty这个文件，理由是natbib与hyperref配合良好，不再需要这个包

**Comment by iphyer** [comment]
可以降级。。。考虑下你学长是４年前写的这个包

**Comment by ZLCao** [comment]
建议安装texlive，宏包会比较全，我的测试也只基于texlive套件。
