### ISSUE TITLE
pageheader 选项无法生成正确的页眉

### ISSUE THREAD

**Issue by zwpwjwtz** [ZLCao/NJUBachelor#4]
我使用
`\documentclass[pageheader, shorttitle]{njubachelor}`
来启用页眉，但是排版出来的页眉中始终有“目录”两个大字，如图所示：

https://wtz.lima-city.de/source/Screenshot_20170519_223318.png

所有的页眉都是这个效果。请问这是什么原因呢？

**Comment by ZLCao** [comment]
我这边编译start文档并没有这个问题，请你加上pageheader选项进行确认。

发送自 Windows 10 版邮件应用

发件人: zwpwjwtz
发送时间: 2017年5月19日 23:08
收件人: ZLCao/NJUBachelor
抄送: Subscribed
主题: [ZLCao/NJUBachelor] pageheader 选项无法生成正确的页眉 (#4)

我使用
\documentclass[pageheader, shorttitle]{njubachelor}
来启用页眉，但是排版出来的页眉中始终有“目录”两个大字，如图所示：
https://wtz.lima-city.de/source/Screenshot_20170519_223318.png
所有的页眉都是这个效果。请问这是什么原因呢？

**Comment by zwpwjwtz** [comment]
我已经启用pageheader选项了啊：
` \documentclass[pageheader, shorttitle]{njubachelor}`

test.tex 的结果是对的。但是test.tex使用了chapter选项，而start.tex默认使用nochapter。
是不是nochapter模式下无法将section的标题复制到页眉上呢？

**Comment by ZLCao** [comment]
重新编译查了一下，请使用\makectitlepage产生中文标题，并声明正文首页的格式。

发送自 Windows 10 版邮件应用

发件人: zwpwjwtz
发送时间: 2017年5月20日 9:40
收件人: ZLCao/NJUBachelor
抄送: Zachary Cao; Comment
主题: Re: [ZLCao/NJUBachelor] pageheader 选项无法生成正确的页眉 (#4)

我已经启用pageheader选项了啊：
\documentclass[pageheader, shorttitle]{njubachelor}
test.tex 的结果是对的。但是test.tex使用了chapter选项，而start.tex默认使用nochapter。
是不是nochapter模式下无法将section的标题复制到页眉上呢？

**Comment by zwpwjwtz** [comment]
我是直接在原来start.tex的基础上改的，并没有删去\makectitlepage。
start.tex的内容如下：
```
\documentclass[pageheader,shorttitle]{njubachelor}

......

\begin{document}

\makectitlepage

\begin{cabstract}
中文摘要。
\end{cabstract}

\begin{eabstract}
English abstract.
\end{eabstract}

\pagenumbering{Roman}
\thispagestyle{plain} %该页一般无页眉
\vspace*{0em}
\maketoc

\newpage
\pagenumbering{arabic}

\thispagestyle{plain} %该页一般无页眉
\makectitle

\section{绪论}

\subsection{课题背景及研究意义}

......
```

**Comment by ZLCao** [comment]
你直接在我模板加上这个选项编译试一下

发自我的 iPhone

**Comment by zwpwjwtz** [comment]
直接编译模板也有问题，不过这个问题并不能直接反应出来，因为你提供的测试内容太短，只够排一页。

如果你把内容弄长一些（比如复制粘贴`\subsection{第二节~第二小节} 主体 2`这一句100次），然后再排版，就能发现问题仍然存在。

还有，我之前说错了，只有正文的页眉上会显示“目录”两个字，其他的页（比如致谢页、参考文献页）都是正常的。不过，附录页的页眉上却仍然是“致谢”。

感觉可能还是nochapter模式下的编号逻辑有问题。

**Comment by ZLCao** [comment]
那可能是我测试不够全面吧，我抽空再测试一下问题在哪儿。

发自我的 iPhone

**Comment by ZLCao** [comment]
我看你好像第一页没有标题，我之前可能笔误了，请确认加入了\makectitle选项，请再仔细参考我的模板。

图片我付在邮件里了。我看你代码似乎也没有问题……不然你把文件发来我测试一下。



发送自 Windows 10 版邮件应用

发件人: zwpwjwtz
发送时间: 2017年5月20日 17:51
收件人: ZLCao/NJUBachelor
抄送: Zachary Cao; Comment
主题: Re: [ZLCao/NJUBachelor] pageheader 选项无法生成正确的页眉 (#4)

直接编译模板也有问题，不过这个问题并不能直接反应出来，因为你提供的测试内容太短，只够排一页。
如果你把内容弄长一些（比如复制粘贴\subsection{第二节~第二小节} 主体 2这一句100次），然后再排版，就能发现问题仍然存在。
还有，我之前说错了，只有正文的页眉上会显示“目录”两个字，其他的页（比如致谢页、参考文献页）都是正常的。不过，附录页的页眉上却仍然是“致谢”。
感觉可能还是nochapter模式下的编号逻辑有问题。

**Comment by zwpwjwtz** [comment]
移植Windows下的字体（Arial、Courier New、SimSun、SimHei、FangSong、KaiTi、FangSong、STSong、STKaiti）后，问题仍然存在。
难道是latex版本的问题？
```
[user@laptop ~]$ xelatex --version
XeTeX 3.14159265-2.6-0.99996 (TeX Live 2016/Arch Linux)
kpathsea version 6.2.2
Copyright 2016 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 59.1; using 59.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.7.1; using 2.7.1
Compiled with Graphite2 version 1.3.9; using 1.3.10
Compiled with HarfBuzz version 1.4.5; using 1.4.6
Compiled with libpng version 1.6.29; using 1.6.29
Compiled with poppler version 0.54.0
Compiled with fontconfig version 2.12.1; using 2.12.1
```

**Comment by ZLCao** [comment]
你用的Arch？用pacman装的吗？

发送自 Windows 10 版邮件应用

发件人: zwpwjwtz
发送时间: 2017年5月21日 22:02
收件人: ZLCao/NJUBachelor
抄送: Zachary Cao; State change
主题: Re: [ZLCao/NJUBachelor] pageheader 选项无法生成正确的页眉 (#4)

移植Windows下的字体（Arial、Courier New、SimSun、SimHei、FangSong、KaiTi、FangSong、STSong、STKaiti）后，问题仍然存在。
难道是latex版本的问题？
[user@laptop ~]$ xelatex --version
XeTeX 3.14159265-2.6-0.99996 (TeX Live 2016/Arch Linux)
kpathsea version 6.2.2
Copyright 2016 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 59.1; using 59.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.7.1; using 2.7.1
Compiled with Graphite2 version 1.3.9; using 1.3.10
Compiled with HarfBuzz version 1.4.5; using 1.4.6
Compiled with libpng version 1.6.29; using 1.6.29
Compiled with poppler version 0.54.0
Compiled with fontconfig version 2.12.1; using 2.12.1

**Comment by zwpwjwtz** [comment]
用的Manjaro，直接用pacman从stable仓库装的。

**Comment by zwpwjwtz** [comment]
有什么好的建议吗？比如直接把页眉右边的标题给去掉？

**Comment by ZLCao** [comment]
@zwpwjwtz 建议用iso安装，各个发行版实在没办法测试到

**Comment by zwpwjwtz** [comment]
我发现可能是\leftmark和\rightmark混淆的问题（njubachelor.dtx，第325行）。
http://bbs.ctex.org/forum.php?mod=viewthread&tid=153020 这里说\leftmark默认生成章标题，\rightmark默认生成节标题。但是在nochapter模式下是没有章的，所以正文中的页眉始终引用的是前一章——也就是“目录”的标题。
所以需要在这里对chapter模式和nochapter模式做出区分。
不过，我还是很好奇为什么Win平台上的TexLive和Linux平台会有这么明显的差异。

**Comment by ZLCao** [comment]
请查阅论文目录部分定义的源代码，我对两种模式的目录标题等级是分别定义的。所以理论上来说nochapter下并没有出现过chapter等级的目录标题。

参考fancyhdr宏包说明，第九页，第九节第一段内容，似乎fancyhdr会自动处理book和article下，mark对应的标题等级问题，所以应该不存在nochapter模式下，硬要去获取一个chapter等级标题的问题才对。

我测试了你修改的文件，发现修改后rightmark获得的是二级标题subsection。

所以虽然你的修改解决了你个人的问题，但为了大多数人的兼容性我无法接受你的合并请求。从我个人经验来看，为了保证最好的兼容性，还是十分推荐你使用iso文件安装texlive系统，发行版的系统包管理安装的系统可能存在各种无法预测的问题。

发送自 Windows 10 版邮件应用

发件人: zwpwjwtz
发送时间: 2017年5月30日 20:37
收件人: ZLCao/NJUBachelor
抄送: Zachary Cao; State change
主题: Re: [ZLCao/NJUBachelor] pageheader 选项无法生成正确的页眉 (#4)

我发现可能是\leftmark和\rightmark混淆的问题（njubachelor.dtx，第325行）。
http://bbs.ctex.org/forum.php?mod=viewthread&tid=153020 这里说\leftmark默认生成章标题，\rightmark默认生成节标题。但是在nochapter模式下是没有章的，所以正文中的页眉始终引用的是前一章——也就是“目录”的标题。
所以需要在这里对chapter模式和nochapter模式做出区分。
不过，我还是很好奇为什么Win平台上的TexLive和Linux平台会有这么明显的差异。

**Comment by zwpwjwtz** [comment]
使用 Debian 9 (Stretch) 测试了一下，仍然有这个问题。
另外，我用TexLive 2017 的 ISO 安装了一下，发现也有这个问题，说明这个确实与平台有关。不知道Latex里面有没有判断当前平台类型的语句？

附：是两个版本的xelatex的版本信息。
```
user@debian:~$ xelatex -v
XeTeX 3.14159265-2.6-0.99996 (TeX Live 2016/Debian)
kpathsea version 6.2.2
Copyright 2016 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 57.1; using 57.1
Compiled with zlib version 1.2.8; using 1.2.8
Compiled with FreeType2 version 2.6.3; using 2.6.3
Compiled with Graphite2 version 1.3.9; using 1.3.10
Compiled with HarfBuzz version 1.4.2; using 1.4.2
Compiled with libpng version 1.6.28; using 1.6.28
Compiled with poppler version 0.48.0
Compiled with fontconfig version 2.11.0; using 2.11.0
 
 
[user@laptop x86_64-linux]$ ./xelatex -v
XeTeX 3.14159265-2.6-0.99998 (TeX Live 2017)
kpathsea version 6.2.3
Copyright 2017 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 58.2; using 58.2
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.7.1; using 2.7.1
Compiled with Graphite2 version 1.3.9; using 1.3.9
Compiled with HarfBuzz version 1.4.6; using 1.4.6
Compiled with libpng version 1.6.29; using 1.6.29
Compiled with poppler version 0.52.0
Compiled with fontconfig version 2.8.0; using 2.12.1
```

**Comment by ZLCao** [comment]
我看过别人写的包，似乎是可以实现一些平台判断的功能的，但当时觉得用xelatex加字体移植应该不需要再考虑平台的问题了，所以没去实现这个功能。但清华和东南的毕业论文模板里似乎涉及过，记得不是很清楚了。

发送自 Windows 10 版邮件应用

发件人: zwpwjwtz
发送时间: 2017年6月20日 23:05
收件人: ZLCao/NJUBachelor
抄送: Zachary Cao; State change
主题: Re: [ZLCao/NJUBachelor] pageheader 选项无法生成正确的页眉 (#4)

使用 Debian 9 (Stretch) 测试了一下，仍然有这个问题。
另外，我用TexLive 2017 的 ISO 安装了一下，发现也有这个问题，说明这个确实与平台有关。不知道Latex里面有没有判断当前平台类型的语句？
附：是两个版本的xelatex的版本信息。
user@debian:~$ xelatex -v
XeTeX 3.14159265-2.6-0.99996 (TeX Live 2016/Debian)
kpathsea version 6.2.2
Copyright 2016 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 57.1; using 57.1
Compiled with zlib version 1.2.8; using 1.2.8
Compiled with FreeType2 version 2.6.3; using 2.6.3
Compiled with Graphite2 version 1.3.9; using 1.3.10
Compiled with HarfBuzz version 1.4.2; using 1.4.2
Compiled with libpng version 1.6.28; using 1.6.28
Compiled with poppler version 0.48.0
Compiled with fontconfig version 2.11.0; using 2.11.0
 
 
[user@laptop x86_64-linux]$ ./xelatex -v
XeTeX 3.14159265-2.6-0.99998 (TeX Live 2017)
kpathsea version 6.2.3
Copyright 2017 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 58.2; using 58.2
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.7.1; using 2.7.1
Compiled with Graphite2 version 1.3.9; using 1.3.9
Compiled with HarfBuzz version 1.4.6; using 1.4.6
Compiled with libpng version 1.6.29; using 1.6.29
Compiled with poppler version 0.52.0
Compiled with fontconfig version 2.8.0; using 2.12.1
